### ISSUE TITLE
jest tester - normalizeResults not defined

### ISSUE THREAD

**Issue by jroehl** [teambit/bit.envs#1]
Hi,

When I try to use the `jest` tester - I get the error `❌   Jest failure - NaNms normalizeResults is not defined`. Is there a problem with version `0.0.26`, or am I doing something wrong? 

Thanks

**Comment by tomlandau** [comment]
hey @jroehl,
It's not you :)
This version is faulty, check out the new version I've just exported - `0.0.27`:

```bash
bit import bit.envs/testers/jest@0.0.27 -t
```

Please reopen if have any further issues.
