### ISSUE TITLE
Typescript version is a year and a half out of date

### ISSUE THREAD

**Issue by dfoverdx** [teambit/bit.envs#15]
My project uses the latest version of typescript.  I can't tag my component because the syntax is "invalid".  Apparently `--force` doesn't skip syntax validation.  `tsc` runs fine.

I thought updating the version of typescript in this repo would fix the issue, but it did not, or I did it wrong.

**Comment by JoshK2** [comment]
@dfoverdx Sorry for waiting so long, we just released a new typescript compiler.
Check out these links:
https://bit.dev/bit/envs/compilers/react-typescript
https://bit.dev/bit/envs/compilers/typescript

**Comment by GiladShoham** [comment]
@dfoverdx Let us know if the new versions solve your problems.
If no, please re-open with more details.
