### ISSUE TITLE
cant use bundlers.vue

### ISSUE THREAD

**Issue by dvelasquez** [teambit/bit.envs#2]
When i run
`bit import bit.envs/compilers/vue -c`
I have this output:
```
C:\Users\Danilo\dev\@dvelasquez\components>bit import bit.envs/compilers/vue -c
error: component "bit.envs/compilers/vue" was not found
```
But i dont have any problem with webpack:
```
C:\Users\Danilo\dev\@dvelasquez\components>bit import bit.envs/bundlers/webpack -c
the following component environments were installed
- bit.envs/bundlers/webpack@0.0.9
```

**Comment by amitgilad3** [comment]
Hi @dvelasquez , you are right . there is a typo in the readme. i fixed it and the correct env is  bit.envs/bundlers/vue
you can also view the component at https://bitsrc.io/bit/envs/bundlers/vue
thanks for pointing this issue out :).
