### ISSUE TITLE
A more readable way to struct the dist file path

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit.envs#46]
I would change this:
https://github.com/teambit/bit.envs/blob/master/components/compilers/typescript/ts.js#L102
`path: path.join(context.name, file.split(path.join(capsuleDir, 'dist'))[1]),`
to something like:
`path.join(context.name, file.relative(path.join(capsuleDir, 'dist'), file),`

(I didn't test the exact line, so need to verify I don't have a mistake here).
This way using relative is more readable than using split and access [1].

**Comment by qballer** [comment]
file is a string, I don't have the relative API on it. 
Also you wanted to remove context.name. Does it still apply.

**Comment by qballer** [comment]
For now I will keep it that way. You are welcomed to  PR after the next release.

**Comment by GiladShoham** [comment]
> file is a string, I don't have the relative API on it

That just a mistake in my snippet, it should be 
`path.join(context.name, path.relative(path.join(capsuleDir, 'dist'), file),`

> Also you wanted to remove context.name. Does it still apply

That still needs to be changed but it's a different issue.

@qballer why do you close it?
just put it with low priority / different milestone / different release. so it won't bother you in the current release.
If you close it, it will be forgotten for sure.

**Comment by qballer** [comment]
Fixed in current compiler.

**Comment by GiladShoham** [comment]
@qballer I still see it even in version 3.0.20

**Comment by qballer** [comment]
make a PR.
