### ISSUE TITLE
get rid of adding context.name (comp name) to the dist path

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit.envs#47]
Adding the comp name directly by the compiler to the dist path is error-prone.
It will make bit's life harder to map the src files to the dist files since their relative path will be different.
This will make some internal features ("magic") of bit to not work properly.
I'm talking about this line:
https://github.com/teambit/bit.envs/blob/master/components/compilers/typescript/ts.js#L102

**Comment by qballer** [comment]
Will be fixed in next version.

**Comment by GiladShoham** [comment]
> Will be fixed in next version

If you plan to do it, close it when you do it. just relate the PR to the issue and it will be closed automatically.
You can set label /priority/milestone to easily filter it for your current work. 

That's an important change. I won't delay it too much, because anyone uses it as it is now is exposed to bugs (and change it later will force users to tag new versions since it is stored in bit's internal db)

**Comment by qballer** [comment]
It's being done in another repo where we don't work with PR. I'm working on that right now.
