### ISSUE TITLE
ts compiler - copy assets / non compiled files to dist folder 

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit.envs#48]
I think it's always better to copy files the compiler doesn't know how to handle as is to the dist files.
Most of the compilers already do this.
This will prevent bugs arrised from accessing assets files of the component for example (since they won't exist in the dist folder of the component).

**Comment by qballer** [comment]
fixed in 3.0.16

**Comment by fabgallo** [comment]
@qballer what about the react-typescript compiler (which was at version v3.0.17)? Is v3.0.19 the one with the fix?

**Comment by GiladShoham** [comment]
@fabgallo From looking on the [dependencies tab](https://bit.dev/bit/envs/compilers/react-typescript/~dependencies) of react-typescript 3.0.19 it seems that it uses typescript 3.0.16 so it should be fine.

**Comment by fabgallo** [comment]
@GiladShoham unfortunately it seems not
![image](https://user-images.githubusercontent.com/2903427/64247812-a2723a00-cedd-11e9-8279-ce2fac20f85d.png)

The compiler is the only thing I changed (`bit import bit.envs/compilers/react-typescript -c`).
If I change the version back to 3.0.1 in `bit.json` it works (even if I use 3.0.17 it compiles no problem, apart for missing the SCSS files)

**Comment by GiladShoham** [comment]
@fabgallo Thanks for reporting this.
Looks like some typo in the code.
I'll ask @qballer to take a look.
Can you open it as a new issue since it's not really related to the copy files issue?
Thanks.

**Comment by fabgallo** [comment]
Will do soon
