### ISSUE TITLE
Jest giving error in test - collection.reduce is not a function

### ISSUE THREAD

**Issue by ruieloi** [teambit/bit.envs#69]
Hi

I'm getting this problem when trying to use (bit.envs/testers/jest).

When I run using this script 

![image](https://user-images.githubusercontent.com/2378539/73964794-cc0b1380-490a-11ea-94b4-6490aad8054a.png)

 all test run good but when I try the "bit test" I get a error in my spec file with the error message 

`\node_modules\jest-haste-map\build\crawlers\node.js:36
      names.forEach(file => {
            ^

TypeError: Cannot read property 'forEach' of undefined`

my spec file is

![image](https://user-images.githubusercontent.com/2378539/73964856-ec3ad280-490a-11ea-9eea-77181d55a2a4.png)

any idea of what's missing?

**Comment by itaymendel** [comment]
Hi,

Sorry for the delayed response. In the last couple of months we've been hard at work on Bit v15. This includes a re-implementation for how Bit tests components which resolves this issue.
I urge you to look into Bit v15 here - https://harmony-docs.bit.dev
